"""Add unique constraint on userid

Revision ID: 10e2819ae05c
Revises: 2390eb49b288
Create Date: 2017-12-14 18:20:48.371106

"""

# revision identifiers, used by Alembic.
revision = '10e2819ae05c'
down_revision = '2390eb49b288'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'player', ['userid_player'])
    op.drop_constraint(u'contract_contractor_id_contract_fkey', 'contract', type_='foreignkey')
    op.drop_constraint(u'contract_target_id_contract_fkey', 'contract', type_='foreignkey')
    op.create_foreign_key(None, 'contract', 'player', ['target_id_contract'], ['userid_player'])
    op.create_foreign_key(None, 'contract', 'player', ['contractor_id_contract'], ['userid_player'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.create_foreign_key(u'contract_target_id_contract_fkey', 'contract', 'player', ['target_id_contract'], ['id_player'])
    op.create_foreign_key(u'contract_contractor_id_contract_fkey', 'contract', 'player', ['contractor_id_contract'], ['id_player'])
    ### end Alembic commands ###
