"""add role stats

Revision ID: 217232acbf89
Revises: 3fb09ade0867
Create Date: 2018-09-04 17:38:40.706454

"""

# revision identifiers, used by Alembic.
revision = '217232acbf89'
down_revision = '3fb09ade0867'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_game', sa.Integer(), nullable=True),
    sa.Column('id_player', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('has_won', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_game'], ['game.id_game'], ),
    sa.ForeignKeyConstraint(['id_player'], ['player.userid_player'], ),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.drop_constraint('gamestats_merlin_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_mordred_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_perceval_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_galahad_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_oberon_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_morgana_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_assassin_fkey', 'gamestats', type_='foreignkey')
    op.drop_column('gamestats', 'merlin')
    op.drop_column('gamestats', 'assassin')
    op.drop_column('gamestats', 'morgana')
    op.drop_column('gamestats', 'perceval')
    op.drop_column('gamestats', 'mordred')
    op.drop_column('gamestats', 'galahad')
    op.drop_column('gamestats', 'oberon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamestats', sa.Column('oberon', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamestats', sa.Column('galahad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamestats', sa.Column('mordred', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamestats', sa.Column('perceval', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamestats', sa.Column('morgana', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamestats', sa.Column('assassin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamestats', sa.Column('merlin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gamestats_assassin_fkey', 'gamestats', 'player', ['assassin'], ['userid_player'])
    op.create_foreign_key('gamestats_morgana_fkey', 'gamestats', 'player', ['morgana'], ['userid_player'])
    op.create_foreign_key('gamestats_oberon_fkey', 'gamestats', 'player', ['oberon'], ['userid_player'])
    op.create_foreign_key('gamestats_galahad_fkey', 'gamestats', 'player', ['galahad'], ['userid_player'])
    op.create_foreign_key('gamestats_perceval_fkey', 'gamestats', 'player', ['perceval'], ['userid_player'])
    op.create_foreign_key('gamestats_mordred_fkey', 'gamestats', 'player', ['mordred'], ['userid_player'])
    op.create_foreign_key('gamestats_merlin_fkey', 'gamestats', 'player', ['merlin'], ['userid_player'])
    op.drop_table('role')
    # ### end Alembic commands ###
