"""Added player and contracts

Revision ID: 2390eb49b288
Revises: 9adeaa93a5a7
Create Date: 2017-12-13 19:17:29.734939

"""

# revision identifiers, used by Alembic.
revision = '2390eb49b288'
down_revision = '9adeaa93a5a7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import withings.datascience.core.sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id_player', sa.Integer(), nullable=False),
    sa.Column('userid_player', sa.Integer(), nullable=False),
    sa.Column('info_player', withings.datascience.core.sqlalchemy_utils.JSONEncodedDict(), nullable=False),
    sa.Column('is_active_player', sa.Boolean(), nullable=False),
    sa.Column('created_player', sa.DateTime(), nullable=False),
    sa.Column('modified_player', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_player')
    )
    op.create_table('contract',
    sa.Column('id_contract', sa.Integer(), nullable=False),
    sa.Column('contractor_id_contract', sa.Integer(), nullable=False),
    sa.Column('target_id_contract', sa.Integer(), nullable=False),
    sa.Column('is_active_contract', sa.Boolean(), nullable=False),
    sa.Column('created_contract', sa.DateTime(), nullable=False),
    sa.Column('modified_contract', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id_contract'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['target_id_contract'], ['player.id_player'], ),
    sa.PrimaryKeyConstraint('id_contract')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    op.drop_table('player')
    ### end Alembic commands ###
