"""Add is ios

Revision ID: 2b531a0dcb77
Revises: b64a1447d6e8
Create Date: 2018-03-20 19:21:37.856045

"""

# revision identifiers, used by Alembic.
revision = '2b531a0dcb77'
down_revision = 'b64a1447d6e8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('is_ios_player', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_ios_player')
    # ### end Alembic commands ###
