"""Renamed two columns

Revision ID: 2e48210b6669
Revises: 10e2819ae05c
Create Date: 2017-12-18 19:28:50.103865

"""

# revision identifiers, used by Alembic.
revision = '2e48210b6669'
down_revision = '10e2819ae05c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('is_completed_contract', sa.Boolean(), nullable=False))
    op.add_column('contract', sa.Column('owner_id_contract', sa.Integer(), nullable=False))
    op.drop_constraint(u'contract_contractor_id_contract_fkey', 'contract', type_='foreignkey')
    op.create_foreign_key(None, 'contract', 'player', ['owner_id_contract'], ['userid_player'])
    op.drop_column('contract', 'contractor_id_contract')
    op.drop_column('contract', 'is_active_contract')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('is_active_contract', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('contract', sa.Column('contractor_id_contract', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.create_foreign_key(u'contract_contractor_id_contract_fkey', 'contract', 'player', ['contractor_id_contract'], ['userid_player'])
    op.drop_column('contract', 'owner_id_contract')
    op.drop_column('contract', 'is_completed_contract')
    ### end Alembic commands ###
