"""Use userids as foreign keys

Revision ID: 3fb09ade0867
Revises: e3555d0d6c67
Create Date: 2018-09-03 20:53:56.771030

"""

# revision identifiers, used by Alembic.
revision = '3fb09ade0867'
down_revision = 'e3555d0d6c67'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gamestats_host_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_morgana_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_merlin_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_galahad_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_mordred_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_oberon_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_assassin_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_perceval_fkey', 'gamestats', type_='foreignkey')
    op.drop_constraint('gamestats_merlin_targeted_fkey', 'gamestats', type_='foreignkey')
    op.create_foreign_key(None, 'gamestats', 'player', ['merlin_targeted'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['merlin'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['morgana'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['perceval'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['oberon'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['galahad'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['assassin'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['mordred'], ['userid_player'])
    op.create_foreign_key(None, 'gamestats', 'player', ['host'], ['userid_player'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.drop_constraint(None, 'gamestats', type_='foreignkey')
    op.create_foreign_key('gamestats_merlin_targeted_fkey', 'gamestats', 'player', ['merlin_targeted'], ['id_player'])
    op.create_foreign_key('gamestats_perceval_fkey', 'gamestats', 'player', ['perceval'], ['id_player'])
    op.create_foreign_key('gamestats_assassin_fkey', 'gamestats', 'player', ['assassin'], ['id_player'])
    op.create_foreign_key('gamestats_oberon_fkey', 'gamestats', 'player', ['oberon'], ['id_player'])
    op.create_foreign_key('gamestats_mordred_fkey', 'gamestats', 'player', ['mordred'], ['id_player'])
    op.create_foreign_key('gamestats_galahad_fkey', 'gamestats', 'player', ['galahad'], ['id_player'])
    op.create_foreign_key('gamestats_merlin_fkey', 'gamestats', 'player', ['merlin'], ['id_player'])
    op.create_foreign_key('gamestats_morgana_fkey', 'gamestats', 'player', ['morgana'], ['id_player'])
    op.create_foreign_key('gamestats_host_fkey', 'gamestats', 'player', ['host'], ['id_player'])
    # ### end Alembic commands ###
