"""Add column version

Revision ID: 68afc4bbfc20
Revises: 7091f13af589
Create Date: 2018-08-29 18:11:13.639307

"""

# revision identifiers, used by Alembic.
revision = '68afc4bbfc20'
down_revision = '7091f13af589'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('version_game', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'version_game')
    # ### end Alembic commands ###
