"""scope 1 try

Revision ID: 76cf4b156836
Revises: af5abce69d3d
Create Date: 2018-01-28 16:54:46.624908

"""

# revision identifiers, used by Alembic.
revision = '76cf4b156836'
down_revision = 'af5abce69d3d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import withings.datascience.core


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id_round', sa.Integer(), nullable=False),
    sa.Column('is_active_round', sa.Boolean(), nullable=False),
    sa.Column('startdate_round', sa.DateTime(), nullable=False),
    sa.Column('enddate_round', sa.DateTime(), nullable=False),
    sa.Column('created_round', sa.DateTime(), nullable=False),
    sa.Column('modified_round', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_round')
    )
    op.add_column(u'contract', sa.Column('info_contract', withings.datascience.core.sqlalchemy_utils.JSONEncodedDict(), nullable=False))
    op.add_column(u'contract', sa.Column('round_id_contract', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contract', 'round', ['round_id_contract'], ['id_round'])
    op.add_column(u'player', sa.Column('is_alive_player', sa.Boolean(), nullable=False))
    op.add_column(u'player', sa.Column('round_points_player', sa.Integer(), nullable=False))
    op.add_column(u'player', sa.Column('token_player', sa.String(), nullable=False))
    op.add_column(u'player', sa.Column('total_points_player', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'player', 'total_points_player')
    op.drop_column(u'player', 'token_player')
    op.drop_column(u'player', 'round_points_player')
    op.drop_column(u'player', 'is_alive_player')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column(u'contract', 'round_id_contract')
    op.drop_column(u'contract', 'info_contract')
    op.drop_table('round')
    # ### end Alembic commands ###
