"""Add URL dor pictures

Revision ID: a07a0bc9cbcc
Revises: 23e875845b95
Create Date: 2018-02-14 18:12:58.097112

"""

# revision identifiers, used by Alembic.
revision = 'a07a0bc9cbcc'
down_revision = '23e875845b95'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('url_128_player', sa.String(), nullable=True))
    op.add_column('player', sa.Column('url_256_player', sa.String(), nullable=True))
    op.add_column('player', sa.Column('url_64_player', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'url_64_player')
    op.drop_column('player', 'url_256_player')
    op.drop_column('player', 'url_128_player')
    # ### end Alembic commands ###
