"""Fixed default value

Revision ID: af5abce69d3d
Revises: 2e48210b6669
Create Date: 2017-12-18 19:56:15.102892

"""

# revision identifiers, used by Alembic.
revision = 'af5abce69d3d'
down_revision = '2e48210b6669'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
