"""Add column date completed

Revision ID: b64a1447d6e8
Revises: 509e7f593458
Create Date: 2018-03-12 10:17:17.208086

"""

# revision identifiers, used by Alembic.
revision = 'b64a1447d6e8'
down_revision = '509e7f593458'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('date_completed_contract', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'date_completed_contract')
    # ### end Alembic commands ###
