"""create gamestats table

Revision ID: e3555d0d6c67
Revises: 68afc4bbfc20
Create Date: 2018-08-31 10:59:37.585772

"""

# revision identifiers, used by Alembic.
revision = 'e3555d0d6c67'
down_revision = '68afc4bbfc20'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamestats',
    sa.Column('id_gamestats', sa.Integer(), nullable=False),
    sa.Column('id_game', sa.Integer(), nullable=True),
    sa.Column('host', sa.Integer(), nullable=True),
    sa.Column('n_players', sa.Integer(), nullable=True),
    sa.Column('good_wins', sa.Boolean(), nullable=False),
    sa.Column('merlin_killed', sa.Boolean(), nullable=True),
    sa.Column('merlin_targeted', sa.Integer(), nullable=True),
    sa.Column('merlin', sa.Integer(), nullable=True),
    sa.Column('perceval', sa.Integer(), nullable=True),
    sa.Column('galahad', sa.Integer(), nullable=True),
    sa.Column('mordred', sa.Integer(), nullable=True),
    sa.Column('morgana', sa.Integer(), nullable=True),
    sa.Column('oberon', sa.Integer(), nullable=True),
    sa.Column('assassin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assassin'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['galahad'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['host'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['id_game'], ['game.id_game'], ),
    sa.ForeignKeyConstraint(['merlin'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['merlin_targeted'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['mordred'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['morgana'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['oberon'], ['player.id_player'], ),
    sa.ForeignKeyConstraint(['perceval'], ['player.id_player'], ),
    sa.PrimaryKeyConstraint('id_gamestats')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamestats')
    # ### end Alembic commands ###
