#!/usr/bin/env python
# -*- coding: utf-8 -*-
import env
import sys
import json

from lib.db import database
from lib import utils
from datetime import datetime

session = database.session()

try:
    userid = sys.argv[1]
    mac = sys.argv[2]
    deviceid = sys.argv[3]

    players = session.query(database.Player).filter_by(userid_player=userid).all()
    if len(players) == 0:
        print "User not found"
        exit()

    p = players[0]
    p.deviceid_player = deviceid
    p.mac_player = mac
    p.previous_deploy_grp_player = 171
    session.commit()
    
    print "Success!"
except Exception, e:
    print e
