#!/usr/bin/env python
# -*- coding: utf-8 -*-
import env
import sys
import json

from lib.db import database
from lib import utils
from datetime import datetime

session = database.session()

try:
    target = sys.argv[1]

    contracts = session.query(database.Contract).filter_by(target_id_contract=target).filter_by(is_active_contract=True).all()
    if len(contracts) > 0:
        print contracts[0].id_contract
    else:
        print "No contract found"

    print "Success!"
except Exception, e:
    print e
