#!/usr/bin/env python
# -*- coding: utf-8 -*-
import env
import sys

from lib.db import database
from lib import utils
from datetime import datetime, timedelta

session = database.session()

players = session.query(database.Player).all()
print "Nb players %d" % len(players)
