#!/usr/bin/env python
# -*- coding: utf-8 -*-
import env
import sys
import json

from lib.db import database
from lib import utils
from datetime import datetime

session = database.session()

try:
    players = session.query(database.Player).filter_by(is_active_player=True).all()
    for p in players:
        contracts = session.query(database.Contract).filter_by(owner_id_contract=p.userid_player).filter_by(is_active_contract=True).all()
        if len(contracts) == 0:
            continue

        c = contracts[0]
        targets = session.query(database.Player).filter_by(userid_player=c.target_id_contract).all()
        if len(targets) == 0:
            continue

        t = targets[0]
        tmp = utils.unlock_clues(c.info_contract, t.info_player)
        utils.send_notif(p.token_player, p.is_ios_player, data_message={"notif_reason": 2}) # refresh
        c.info_contract["api"] = tmp["api"]
        c.info_contract["survey"] = tmp["survey"]

    session.commit()
    print "Success!"
except Exception, e:
    print e
