#!/usr/bin/env python

import env
from lib.worker import ExampleWorker
from withings.datascience.core import config, setup_logging

setup_logging('worker.datascience.example')

w = ExampleWorker(hosts=config.get('main', 'beanstalk_hosts').split(','),
                  tube='datascience-example')
w.run()
